# Generated by Django 5.2.8 on 2025-11-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='description',
            field=models.TextField(blank=True, help_text='Room description', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(blank=True, help_text='Room name (required for groups, auto-generated for private)', max_length=100),
        ),
    ]
